spring.datasource.url=jdbc:mysql://vickyadmin.cx8ywmuk4eqw.ap-south-1.rds.amazonaws.com/Vickysql
spring.datasource.username=vicky
spring.datasource.password=Venkatesh@##123
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Jpa properties /Hb related properties
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.port=8082
spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=300MB
spring.mvc.hiddenmethod.filter.enabled=true

